
name: test:audit

on:
  push:
    paths:
    - '.github/workflows/audit.yml'
    - 'action.yml'
    - 'Cask/jira-cli.rb'
  workflow_dispatch:

jobs:
  test-run:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Audit Cask
      run: |
        cask=Cask/jira-cli.rb
        brew update
        brew audit --cask --online $cask
        brew style --fix $cask
        brew install --cask $cask
        brew uninstall --cask $cask
